version: "3.3"
services:
  server:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: postgres
      POSTGRES_HOST: postgres
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: nab-test/server:latest
    ports:
      - "8081:8081"
    stdin_open: true
    tty: true
    depends_on:
      - postgres
  postgres:
    image: postgres:9.6.1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: postgres
